name = input("Friend's Name: ")
nickname = input("Nickname: ")
color = input("Favorite Color: ")
dream = input("Dream: ")
person = input("Favorite Person: ")
food = input("Favorite Food: ")

print("\n--- Slam Book Entry ---")
print("Name:", name)
print("Nickname:", nickname)
print("Favorite Color:", color)
print("Dream:", dream)
print("Favorite Person:", person)
print("Favorite Food:", food)
